language: ruby

rvm:
 - 2.7.1

cache:
  - bundler
  - yarn

before_install:
  - gem install bundler

services:
  - postgresql

script:
  - bundle install --jobs=3 --retry=3
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec

before_script:
  - cp config/database.travis.yml config/database.yml
